"""adding a manager to the team

Revision ID: 3a8e7472f5e9
Revises: 1fa8ccf15f67
Create Date: 2025-10-04 16:07:46.427950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8e7472f5e9'
down_revision: Union[str, Sequence[str], None] = '1fa8ccf15f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'manager_id')
    # ### end Alembic commands ###
